### ISSUE TITLE
Is there a way to convert a Xema schema to a JsonXema ?

### ISSUE THREAD

**Issue by lud** [hrzndhrn/json_xema#18]
I would like to define some datastructures with Xema, because the code handling the data will be in elixir.

But _some_ of the structures will be sent to and received from a browser, and for those structures I would like to use JsonXema. But I do not want to define those schemas twice.

Because I am lazy, but let us say it is to avoid mismatchs between two sources of truth.

**Comment by NickNeck** [comment]
For now, there is no function to convert `Xema` to `JsonXema`. But you don't need `JsonXema` to validate data from a Browser, you can validate this data also with `Xema`:
```elixir
with {:ok, data} <- Jason.decode(json),
     :ok <- Xema.validate(my_schema, data) do
...
``` 
You can also convert Json data with `Xema`, see https://hexdocs.pm/xema/examples.html#cast-json

**Comment by lud** [comment]
Well I would like to publish the `Xema` schema as json-schema data for tools like Swagger UI. I think you two libraries should be just one actually !

But that is ok, thanks for the info !
