### ISSUE TITLE
Any reason to convert fields to camel case?

### ISSUE THREAD

**Issue by AlexKovalevych** [hrzndhrn/json_xema#19]
Having such example:

```
iex(8)> schema
%JsonXema{
  refs: %{},
  schema: %Xema.Schema{
    additional_properties: false,
    properties: %{
      "first_name" => %Xema.Schema{data: %{"min_length" => 3}, type: :string}
    },
    required: #MapSet<["first_name"]>,
    type: :map
  }
}
iex(9)> schema |> JsonXema.validate(%{})
{:error,
 %JsonXema.ValidationError{message: nil, reason: %{required: ["firstName"]}}}
```

`first_name` is a required field, but in validation error it converts to camel case for some reason

**Comment by NickNeck** [comment]
No, there is no reason for that. That is just a bug. Thank you for reporting that.
`JsonXema` has used `Xema` and for this reason, some JSON Schema keywords are converted and it seems that this leads to the error.
