### ISSUE TITLE
Potential issue w/ uri-reference format checking and nested query parameters

### ISSUE THREAD

**Issue by zachdaniel** [hrzndhrn/json_xema#26]
```
iex(8)> JsonXema.new(%{"format" => "uri-reference"}) |> JsonXema.validate("http://www.example.com/posts?page[limit]=20")
{:error,
 %JsonXema.ValidationError{
   message: nil,
   reason: %{
     format: "uri-reference",
     value: "http://www.example.com/posts?page[limit]=20"
   }
 }}
```

AFAIK the URI should be valid, right? Or does json schema uri-reference not support nested query parameters like that? If I don't include nested query parameters then everything works fine.

**Comment by zachdaniel** [comment]
It looks like I could just URI encode the links and then everything works also.

**Comment by NickNeck** [comment]
Thanks for your input!

Format `uri-reference` validates a string according to [RFC3986, section 4.1](https://tools.ietf.org/html/rfc3986#section-4.1). That means that the characters `[` and `]` are not valid and must be encoded as `%5B` and `%5D`. See also [Collected ABNF for URI](https://tools.ietf.org/html/rfc3986#appendix-A).

**Comment by zachdaniel** [comment]
Thats a bummer :) For my purposes, I'll probably break the spec I'm working with, then, as I don't see a benefit of encoding URI characters in my case.  Thanks for explaining!
