### ISSUE TITLE
Infinite loop while loading a schema mentioning a remote one which is self-referential

### ISSUE THREAD

**Issue by depressed-pho** [hrzndhrn/json_xema#37]
`JsonXema.new()` enters into an infinite loop while loading `test.parent.schema.json` shown below:

`test.parent.schema.json`:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref":    "test.child.schema.json"
}
```

`test.child.schema.json`:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$ref":    "#/definitions/self",
    "definitions": {
        "self": {
            "type": "object",
            "properties": {
                "a": {"type": "string"},
                "b": {"$ref": "#/definitions/self"}
            }
        }
    }
}
```

If instead I directly load `test.child.schema.json`, the problem does not happen. Tested on Xema-0.13.3, JsonXema-0.6.0.

**Comment by NickNeck** [comment]
Thanks for the report. I will take a look as soon as possible.

**Comment by NickNeck** [comment]
@depressed-pho the inline feature causes the infinite loop. Until I fixed that, you can set `inline: false` as a workaround.

**Comment by NickNeck** [comment]
Fixed in https://github.com/hrzndhrn/xema/pull/142 
New `xema` version 0.13.7 published.
