### ISSUE TITLE
Fails on valid schema url

### ISSUE THREAD

**Issue by vooolll** [hrzndhrn/json_xema#45]
when:

http://json-schema.org/draft-07/schema or
https://json-schema.org/draft-07/schema

value set in "$schema" field in json schema, library can't recognise json schema and fails with an error.

Searching in sources helped to understand that magical value is - `http://json-schema.org/draft-07/schema#`

Probably it's a bug

**Comment by NickNeck** [comment]
Thanks for reporting. I will have a look.
