### ISSUE TITLE
Only specif recode dependency for dev/test environment

### ISSUE THREAD

**Issue by gmile** [hrzndhrn/json_xema#47]
After upgrading to 0.6.3, a bunch of new dependencies appeared in our mix.lock file, namely: escape, glob_ex, recode, rewrite, sourceror. It looks like they appeared after https://github.com/hrzndhrn/json_xema/commit/74d57323289e3a7e30c7234508d8d05b96df9b40, which adds recode. 

Since `recode` is a linter tool, should is be marked as dev/test only dependency to prevent being pulled into projects that merely depend on json_xema?

**Comment by NickNeck** [comment]
Thank you very much for reporting this. A new version is on the way.

**Comment by NickNeck** [comment]
closed by 8d31320
